# Generated by Django 2.1.2 on 2018-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181106_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
