# Generated by Django 2.1.2 on 2018-11-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181106_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='request_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='response_date',
            field=models.DateTimeField(null=True),
        ),
    ]
