# Generated by Django 2.1.2 on 2018-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181109_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
