# Generated by Django 2.1.2 on 2018-11-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_status_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='request_date',
            new_name='request_datetime',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='response_date',
            new_name='response_datetime',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='status_comment',
            old_name='date',
            new_name='datetime',
        ),
    ]
