# Generated by Django 2.1.2 on 2018-11-11 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status_comments', models.BooleanField(null=True)),
                ('friends', models.BooleanField(null=True)),
                ('discussions', models.BooleanField(null=True)),
                ('events', models.BooleanField(null=True)),
                ('groups', models.BooleanField(null=True)),
            ],
        ),
    ]
