# Generated by Django 2.1.2 on 2018-11-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='discussions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='events',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='status_comments',
            field=models.BooleanField(default=False),
        ),
    ]
