# Generated by Django 2.1.2 on 2018-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181113_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
