# Generated by Django 2.1.2 on 2018-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181119_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='address',
            field=models.BooleanField(default=False),
        ),
    ]
