# Generated by Django 2.1.2 on 2018-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_privacy_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status_comment',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='privacy',
            name='contact',
            field=models.BooleanField(default=False),
        ),
    ]
