# Generated by Django 2.1.2 on 2018-11-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181126_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
