# Generated by Django 2.1.2 on 2018-11-28 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20181106_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
                ('request_datetime', models.DateTimeField(auto_now=True)),
                ('response_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(default='request', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations_receipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
