# Generated by Django 2.1.2 on 2018-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20181106_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion_comment',
            name='date',
        ),
        migrations.AddField(
            model_name='discussion_comment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
