# Generated by Django 2.1.2 on 2018-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_discussion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion_comment',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
